-- AlterTable
ALTER TABLE "Product" ALTER COLUMN "minStock" SET DEFAULT 0,
ALTER COLUMN "minStock" SET DATA TYPE DECIMAL(18,3),
ALTER COLUMN "maxStock" SET DATA TYPE DECIMAL(18,3);

-- AlterTable
ALTER TABLE "ProductStock" ALTER COLUMN "minStock" SET DEFAULT 0,
ALTER COLUMN "minStock" SET DATA TYPE DECIMAL(18,3),
ALTER COLUMN "maxStock" SET DATA TYPE DECIMAL(18,3);
